'use server';
/**
 * @fileOverview A flow for generating grounded agent responses.
 *
 * - agentResponse - A function that generates an answer based on context.
 * - AgentResponseInput - The input type for the flow.
 * - AgentResponseOutput - The return type for the flow.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ContextChunkSchema = z.object({
  title: z.string(),
  text: z.string(),
  url: z.string().optional(),
});

const AgentResponseInputSchema = z.object({
  query: z.string().describe('The user\'s latest question.'),
  botName: z.string().describe('The name of the AI agent.'),
  context: z.array(ContextChunkSchema).describe('Relevant information retrieved from the knowledge base.'),
  greetingScript: z.string().optional().describe('An optional custom greeting or instruction for this specific channel.'),
});
export type AgentResponseInput = z.infer<typeof AgentResponseInputSchema>;

const AgentResponseOutputSchema = z.object({
  answer: z.string().describe('The natural language response generated by the AI.'),
});
export type AgentResponseOutput = z.infer<typeof AgentResponseOutputSchema>;

export async function agentResponse(input: AgentResponseInput): Promise<AgentResponseOutput> {
  return agentResponseFlow(input);
}

const prompt = ai.definePrompt({
  name: 'agentResponsePrompt',
  input: {schema: AgentResponseInputSchema},
  output: {schema: AgentResponseOutputSchema},
  prompt: `You are {{{botName}}}, a helpful AI assistant. Your goal is to provide accurate and helpful answers based ONLY on the provided context.

**Custom Instructions/Greeting:**
{{{greetingScript}}}

**Context Information:**
{{#each context}}
---
Title: {{{title}}}
Content: {{{text}}}
Source: {{{url}}}
---
{{/each}}

**User Question:**
"{{{query}}}"

**Guidelines:**
1. Use the provided context to answer the question as clearly and concisely as possible.
2. If the answer is not in the context, politely state that you don't have that information and offer to connect them to a human agent.
3. Use Markdown for formatting (bold, lists, etc.) to make the answer readable.
4. Do not invent facts or mention information outside of the provided context.
5. If sources are provided, you can mention them naturally if helpful.
`,
});

const agentResponseFlow = ai.defineFlow(
  {
    name: 'agentResponseFlow',
    inputSchema: AgentResponseInputSchema,
    outputSchema: AgentResponseOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
