'use server';
/**
 * @fileOverview A flow for generating grounded agent responses.
 *
 * - agentResponse - A function that generates an answer based on context.
 * - AgentResponseInput - The input type for the flow.
 * - AgentResponseOutput - The return type for the flow.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ContextChunkSchema = z.object({
  sourceId: z.string().describe('Stable ID for the source chunk.'),
  sourceType: z.enum(['article', 'topic', 'insight', 'chunk']).describe('Source category for this chunk.'),
  title: z.string(),
  text: z.string(),
  url: z.string().optional(),
});

const ChatHistoryItemSchema = z.object({
  role: z.enum(['user', 'assistant']),
  content: z.string(),
});

const AgentResponseInputSchema = z.object({
  query: z.string().describe('The user\'s latest question.'),
  botName: z.string().describe('The name of the AI agent.'),
  context: z.array(ContextChunkSchema).describe('Relevant information retrieved from the knowledge base.'),
  greetingScript: z.string().optional().describe('An optional custom greeting or instruction for this specific channel.'),
  history: z.array(ChatHistoryItemSchema).optional().describe('Recent conversation history (last few turns) for context.'),
});
export type AgentResponseInput = z.infer<typeof AgentResponseInputSchema>;

const AgentResponseOutputSchema = z.object({
  answer: z.string().describe('The natural language response generated by the AI.'),
  showSources: z.boolean().describe('True only when the provided context directly answers the user question and source links should be shown.'),
  selectedSourceIds: z
    .array(z.string())
    .describe('Source IDs from context that directly support the final answer. Return [] when no source should be shown.'),
  requestsHumanHandoff: z.boolean().describe('True if the user wants to be connected to a human agent or team member — either explicitly ("talk to human", "connect me") or implicitly (e.g. saying "yes", "sure", "ok", "go ahead" in response to the bot offering to connect them with the team).'),
});
export type AgentResponseOutput = z.infer<typeof AgentResponseOutputSchema>;

export async function agentResponse(input: AgentResponseInput): Promise<AgentResponseOutput> {
  return agentResponseFlow(input);
}

const prompt = ai.definePrompt({
  name: 'agentResponsePrompt',
  input: {schema: AgentResponseInputSchema},
  output: {schema: AgentResponseOutputSchema},
  prompt: `You are {{{botName}}}, a helpful AI assistant. Your goal is to give helpful, natural replies.

**Agent Instructions & Business Knowledge (HIGHEST PRIORITY — always use this to answer if relevant):**
{{{greetingScript}}}

**Additional Context from Knowledge Base:**
{{#each context}}
---
Source ID: {{{sourceId}}}
Source Type: {{{sourceType}}}
Title: {{{title}}}
Content: {{{text}}}
Source: {{{url}}}
---
{{/each}}

{{#if history}}
**Recent Conversation History:**
{{#each history}}
{{role}}: {{{content}}}
{{/each}}
{{/if}}

**User Question:**
"{{{query}}}"

**Guidelines:**
1. ALWAYS check the Agent Instructions & Business Knowledge section first. If it contains an answer (business hours, products, FAQs, delivery info, pricing, etc.) — use it directly. This is your primary knowledge source.
2. If the Agent Instructions don't cover the question, check the Additional Context from the Knowledge Base.
3. IMPORTANT: Check the Recent Conversation History. If the user's question was already answered by a team member or assistant earlier in this conversation, summarize or repeat that answer. Do NOT treat it as off-topic just because it falls outside the business scope.
4. Keep tone natural, friendly, and concise. Avoid robotic phrasing.
5. If the user asks a how-to question and context contains steps, provide a clear numbered step-by-step answer.
6. Only redirect to your support scope if the question has NO answer in Agent Instructions, Knowledge Base, OR conversation history.
7. Do NOT use defensive or uncertainty disclaimers such as:
  - "From what I understand"
  - "My knowledge is limited"
  - "I can't provide"
  - "I don't have enough information"
  - "Based on the documentation I have"
  - "Based on our documentation"
  - "According to our documentation"
  - "It appears"
  - "It seems"
8. Do NOT mention internal retrieval limits (for example: "no context found", "knowledge base does not contain", "documentation says").
9. For off-topic queries, use this style:
  - One short direct line about the topic (if it's common general knowledge),
  - Then one short support redirection line,
  - No apology-heavy wording.
10. Keep off-topic replies short (max 2-3 sentences total).
11. Set showSources=true ONLY when the Additional Context from Knowledge Base directly supports the actual answer.
12. Set showSources=false when answering from Agent Instructions or when context is weakly related, ambiguous, or off-topic.
13. Always return selectedSourceIds.
14. If showSources=false, selectedSourceIds must be [].
15. If showSources=true, selectedSourceIds must include only Source ID values from Additional Context that were actually used to answer.
16. Never include unrelated Source ID values.
17. Keep selectedSourceIds focused and short (max 3 IDs).
18. Set requestsHumanHandoff=true when the user's intent is clearly to talk to a real person. This includes:
   - Direct requests: "talk to human", "connect me", "I want to speak with someone", "can I chat with your team"
   - Acceptance responses: "yes", "sure", "ok", "please", "go ahead", "yes please", "that would be great" — when the previous bot message offered to connect them with the team
   - Any phrasing that clearly accepts or asks for human assistance
19. Set requestsHumanHandoff=false for all other cases, including general questions, follow-up questions, or off-topic queries.
`,
});

const agentResponseFlow = ai.defineFlow(
  {
    name: 'agentResponseFlow',
    inputSchema: AgentResponseInputSchema,
    outputSchema: AgentResponseOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
