'use server';
/**
 * @fileOverview A flow for generating grounded agent responses.
 *
 * - agentResponse - A function that generates an answer based on context.
 * - AgentResponseInput - The input type for the flow.
 * - AgentResponseOutput - The return type for the flow.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ContextChunkSchema = z.object({
  sourceId: z.string().describe('Stable ID for the source chunk.'),
  sourceType: z.enum(['article', 'topic', 'insight', 'chunk']).describe('Source category for this chunk.'),
  title: z.string(),
  text: z.string(),
  url: z.string().optional(),
});

const AgentResponseInputSchema = z.object({
  query: z.string().describe('The user\'s latest question.'),
  botName: z.string().describe('The name of the AI agent.'),
  context: z.array(ContextChunkSchema).describe('Relevant information retrieved from the knowledge base.'),
  greetingScript: z.string().optional().describe('An optional custom greeting or instruction for this specific channel.'),
});
export type AgentResponseInput = z.infer<typeof AgentResponseInputSchema>;

const AgentResponseOutputSchema = z.object({
  answer: z.string().describe('The natural language response generated by the AI.'),
  showSources: z.boolean().describe('True only when the provided context directly answers the user question and source links should be shown.'),
  selectedSourceIds: z
    .array(z.string())
    .describe('Source IDs from context that directly support the final answer. Return [] when no source should be shown.'),
});
export type AgentResponseOutput = z.infer<typeof AgentResponseOutputSchema>;

export async function agentResponse(input: AgentResponseInput): Promise<AgentResponseOutput> {
  return agentResponseFlow(input);
}

const prompt = ai.definePrompt({
  name: 'agentResponsePrompt',
  input: {schema: AgentResponseInputSchema},
  output: {schema: AgentResponseOutputSchema},
  prompt: `You are {{{botName}}}, a friendly support assistant. Your goal is to give helpful, natural replies.

**Custom Instructions/Greeting:**
{{{greetingScript}}}

**Context Information:**
{{#each context}}
---
Source ID: {{{sourceId}}}
Source Type: {{{sourceType}}}
Title: {{{title}}}
Content: {{{text}}}
Source: {{{url}}}
---
{{/each}}

**User Question:**
"{{{query}}}"

**Guidelines:**
1. Prefer using the provided context when it clearly matches the user question.
2. Keep tone natural, friendly, and concise. Avoid robotic phrasing.
3. If the user asks a how-to question and context contains steps, provide a clear numbered step-by-step answer.
4. If the question is off-topic or not directly supported by the context:
  - Give a brief, high-level reply in 1-2 lines.
  - Then gently redirect to your support scope (for example: "I mainly help with support/account/product questions. If you want, I can help with that.").
5. Do NOT use defensive or uncertainty disclaimers such as:
  - "From what I understand"
  - "My knowledge is limited"
  - "I can't provide"
  - "I don't have enough information"
  - "Based on the documentation I have"
6. Do NOT mention internal retrieval limits (for example: "no context found", "knowledge base does not contain", "documentation says").
7. For off-topic queries, use this style:
  - One short direct line about the topic (if it's common general knowledge),
  - Then one short support redirection line,
  - No apology-heavy wording.
8. Keep off-topic replies short (max 2-3 sentences total).
9. Set showSources=true ONLY when the context directly supports the actual answer.
10. Set showSources=false when context is weakly related, ambiguous, or off-topic to the user question.
11. Always return selectedSourceIds.
12. If showSources=false, selectedSourceIds must be [].
13. If showSources=true, selectedSourceIds must include only Source ID values from Context Information that were actually used to answer.
14. Never include unrelated Source ID values.
15. Keep selectedSourceIds focused and short (max 3 IDs).
`,
});

const agentResponseFlow = ai.defineFlow(
  {
    name: 'agentResponseFlow',
    inputSchema: AgentResponseInputSchema,
    outputSchema: AgentResponseOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
